# Generated by Django 6.0.4 on 2026-04-20 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название дома')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram chat_id')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер обращения')),
                ('status', models.CharField(choices=[('accepted', 'Принято'), ('in_progress', 'В работе'), ('need_info', 'Нужна информация'), ('done', 'Выполнено'), ('rejected', 'Отклонено')], default='accepted', max_length=20, verbose_name='Статус')),
                ('type', models.CharField(choices=[('emergency', 'Авария'), ('complaint', 'Жалоба'), ('request', 'Заявка'), ('question', 'Вопрос'), ('proposal', 'Предложение')], max_length=20, verbose_name='Тип')),
                ('entrance', models.CharField(blank=True, default='', max_length=10, verbose_name='Подъезд')),
                ('apartment', models.CharField(blank=True, default='', max_length=10, verbose_name='Квартира')),
                ('text', models.TextField(verbose_name='Текст обращения')),
                ('media', models.URLField(blank=True, default='', verbose_name='Медиа')),
                ('contact', models.CharField(blank=True, default='', max_length=200, verbose_name='Контакт')),
                ('sentiment', models.CharField(choices=[('negative', 'Негативная'), ('neutral', 'Нейтральная'), ('positive', 'Позитивная')], default='neutral', max_length=20, verbose_name='Тональность')),
                ('summary', models.CharField(blank=True, default='', max_length=500, verbose_name='Суть')),
                ('comment_to_resident', models.TextField(blank=True, default='', verbose_name='Комментарий жителю')),
                ('internal_comment', models.TextField(blank=True, default='', verbose_name='Внутренний комментарий')),
                ('resident_tg_id', models.BigIntegerField(blank=True, null=True, verbose_name='TG ID жителя')),
                ('message_id', models.IntegerField(blank=True, null=True, verbose_name='TG message_id')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='TG chat_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='dispatcher.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
            },
        ),
    ]
